### ISSUE TITLE
Enable prometheus metrics endpoint

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-sso#30]
We can use something like this https://github.com/iadvize/traefik-exporter

**Comment by limed** [comment]
Requires investigation but it looks like prometheus exporting of metrics might be already possible. Read: https://www.brianchristner.io/how-to-monitor-traefik-reverse-proxy-with-prometheus/amp/

**Comment by gozer** [comment]
You are correct, all we need is 
```
[web.metrics.prometheus]
```
In our config and #32 

From: https://docs.traefik.io/configuration/backends/web/#metrics
