### ISSUE TITLE
Reloading nubis admin/sso dashboard fails with various SSO-related errors

### ISSUE THREAD

**Issue by ziegeer** [nubisproject/nubis-sso#9]
Once you've opened the dashboard for a Nubis admin site such as https://sso.admin.us-west-2.appsvcs-generic.nubis.allizom.org/ and it's sat long enough to timeout on SSO, reloading it often fails with various errors such as:

> Error:
> 
> Invalid Authentication Response
> 
> Description:
> 
> This is due to a timeout; please restart your authentication session by re-entering the URL/bookmark you originally wanted to access: https://sso.admin.us-west-2.appsvcs-generic.nubis.allizom.org/bottom.shtml

or a 401 Unauthorized or a 500 ISE.  Reloading doesn't help, I have to close the tab and reopen the Nubis url and right now even that isn't working.  If I load it in a private window it works, which seems to imply a cookie I have from the Nubis sso is causing problems.  Clearing cookies and reloading, I have to reauth through Auth0 as expected and then I get a Unauthorized warning:

> Unauthorized
> 
> This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

**Comment by ziegeer** [comment]
Ah I figured out the Unauthorized part, Auth0 was stuck on using my Mozilla Google account which wouldn't work but LDAP does.

**Comment by ziegeer** [comment]
This continues to be a frequent problem.  After restarting my browser for an update, my already-open tab for sso admin on appsvcs-generic gave this Auth0 error message: https://www.dropbox.com/s/2rif0d68427c9n4/Screenshot%202017-09-05%2014.10.50.png?dl=0

Trying to reload the tab stays at that error page, trying to navigate back results in a 500 ISE.  I've tried clearing cookies and restarting the browser in the past to solve this issue but have yet to find a reliable workaround.

**Comment by ziegeer** [comment]
As an added note, I do not see this error ever on any other SSO site, Auth0 or Okta, only on Nubis admin sites so there appears to be some sort of session and/or cookie handling issue here.

**Comment by gozer** [comment]
What happens if you just go and hit

https://sso.admin.us-west-2.appsvcs-generic.nubis.allizom.org/

Directly once that has happened ?

**Comment by ziegeer** [comment]
That works!  I see now that the tab I had open has SSO state in the url and that likely is old and causing problems somehow.  It looks like:

https://sso.admin.us-west-2.appsvcs-generic.nubis.allizom.org/sso?code=fhQhSlfZhVefbQWu&state=q_GT8BFxs_rXe_5Y7e2T9lD8rwjiKSmN

To be clear, after receiving the auth0 error and trying to navigate backwards (as it's hard to even tell what site the tab was open to) the above is the url that it shows (and returns 500s).
